import type { Screen } from './project'
import { makeZip } from './zip'
import { buildProjectFiles, type ExportOptions } from './export/project'

/** Turn an arbitrary name into a safe PascalCase identifier for a filename. */
export function pascalCase(input: string): string {
  const words = input
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
  const pascal = words.map((w) => w.charAt(0).toUpperCase() + w.slice(1)).join('')
  if (!pascal) return 'Screen'
  return /^[0-9]/.test(pascal) ? 'Screen' + pascal : pascal
}

/** A component's base filename (no extension), preferring a valid component identifier. */
export function fileBaseFor(screen: Screen): string {
  const fromComponent = /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(screen.componentName)
    ? screen.componentName
    : ''
  return fromComponent || pascalCase(screen.name)
}

/** The .tsx source for one screen, with a small provenance header. */
export function tsxFor(screen: Screen): string {
  const header = [
    '/*',
    ` * ${fileBaseFor(screen)} — generated by Mocky`,
    ` * Prompt: ${screen.prompt.replace(/\s+/g, ' ').trim()}`,
    ` * ${new Date(screen.createdAt).toISOString()}`,
    ' */',
    '',
  ].join('\n')
  return header + screen.code.trimEnd() + '\n'
}

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}

/** Download a single screen as `<Component>.tsx`. */
export function downloadTsx(screen: Screen): void {
  const blob = new Blob([tsxFor(screen)], { type: 'text/plain;charset=utf-8' })
  triggerDownload(blob, `${fileBaseFor(screen)}.tsx`)
}

/**
 * Export the screens as a RUNNABLE Vite + React + Tailwind project (see
 * export/project.ts). Async because rewriting each screen to explicit ESM uses
 * Babel to analyze scope. `zipName` defaults to the project name.
 */
export async function downloadZip(
  screens: Screen[],
  opts: ExportOptions,
  zipName?: string,
): Promise<void> {
  const files = await buildProjectFiles(screens, opts)
  const name = (opts.projectName || 'mocky-app').replace(/[^a-zA-Z0-9-_]+/g, '-').toLowerCase() || 'mocky-app'
  triggerDownload(makeZip(files), zipName ?? `${name}.zip`)
}
