// GENERATED by worker/video/scripts/fonts.mjs — what each installed family is, and how wide it sets. Do not edit by hand:
// change the family list there and run it again (its header says how).

/** The two unicode ranges each face is split into, as fontsource ships them. */
export const UNICODE_RANGES = {
  "latin": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
  "latinExt": "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF"
}

/**
 * One entry per family. `advance` is the worst ratio of its width to Liberation Sans on
 * the sample sentences, at weights 400 and 800 — see the script for the method.
 */
export const FONT_CATALOGUE = [
  {
    "family": "Inter",
    "category": "sans-serif",
    "advance": 1.051,
    "faces": [
      {
        "key": "inter-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Inter Tight",
    "category": "sans-serif",
    "advance": 0.98,
    "faces": [
      {
        "key": "inter-tight-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Manrope",
    "category": "sans-serif",
    "advance": 1.012,
    "faces": [
      {
        "key": "manrope-wght",
        "weight": "200 800"
      }
    ]
  },
  {
    "family": "Space Grotesk",
    "category": "sans-serif",
    "advance": 1.04,
    "faces": [
      {
        "key": "space-grotesk-wght",
        "weight": "300 700"
      }
    ]
  },
  {
    "family": "DM Sans",
    "category": "sans-serif",
    "advance": 1.015,
    "faces": [
      {
        "key": "dm-sans-wght",
        "weight": "100 1000"
      }
    ]
  },
  {
    "family": "Plus Jakarta Sans",
    "category": "sans-serif",
    "advance": 1.023,
    "faces": [
      {
        "key": "plus-jakarta-sans-wght",
        "weight": "200 800"
      }
    ]
  },
  {
    "family": "Outfit",
    "category": "sans-serif",
    "advance": 0.966,
    "faces": [
      {
        "key": "outfit-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Sora",
    "category": "sans-serif",
    "advance": 1.1,
    "faces": [
      {
        "key": "sora-wght",
        "weight": "100 800"
      }
    ]
  },
  {
    "family": "Syne",
    "category": "sans-serif",
    "advance": 1.632,
    "faces": [
      {
        "key": "syne-wght",
        "weight": "400 800"
      }
    ]
  },
  {
    "family": "Work Sans",
    "category": "sans-serif",
    "advance": 1.088,
    "faces": [
      {
        "key": "work-sans-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "IBM Plex Sans",
    "category": "sans-serif",
    "advance": 0.994,
    "faces": [
      {
        "key": "ibm-plex-sans-wght",
        "weight": "100 700"
      }
    ]
  },
  {
    "family": "Figtree",
    "category": "sans-serif",
    "advance": 0.993,
    "faces": [
      {
        "key": "figtree-wght",
        "weight": "300 900"
      }
    ]
  },
  {
    "family": "Rubik",
    "category": "sans-serif",
    "advance": 1.056,
    "faces": [
      {
        "key": "rubik-wght",
        "weight": "300 900"
      }
    ]
  },
  {
    "family": "Montserrat",
    "category": "sans-serif",
    "advance": 1.11,
    "faces": [
      {
        "key": "montserrat-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Open Sans",
    "category": "sans-serif",
    "advance": 1.063,
    "faces": [
      {
        "key": "open-sans-wght",
        "weight": "300 800"
      }
    ]
  },
  {
    "family": "Roboto",
    "category": "sans-serif",
    "advance": 0.979,
    "faces": [
      {
        "key": "roboto-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Raleway",
    "category": "sans-serif",
    "advance": 1.015,
    "faces": [
      {
        "key": "raleway-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Archivo",
    "category": "sans-serif",
    "advance": 1.035,
    "faces": [
      {
        "key": "archivo-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Urbanist",
    "category": "sans-serif",
    "advance": 0.947,
    "faces": [
      {
        "key": "urbanist-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Lexend",
    "category": "sans-serif",
    "advance": 1.097,
    "faces": [
      {
        "key": "lexend-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Onest",
    "category": "sans-serif",
    "advance": 1.029,
    "faces": [
      {
        "key": "onest-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Geist",
    "category": "sans-serif",
    "advance": 1.033,
    "faces": [
      {
        "key": "geist-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Instrument Sans",
    "category": "sans-serif",
    "advance": 1.004,
    "faces": [
      {
        "key": "instrument-sans-wght",
        "weight": "400 700"
      }
    ]
  },
  {
    "family": "Bricolage Grotesque",
    "category": "sans-serif",
    "advance": 1.021,
    "faces": [
      {
        "key": "bricolage-grotesque-wght",
        "weight": "200 800"
      }
    ]
  },
  {
    "family": "Schibsted Grotesk",
    "category": "sans-serif",
    "advance": 1.033,
    "faces": [
      {
        "key": "schibsted-grotesk-wght",
        "weight": "400 900"
      }
    ]
  },
  {
    "family": "Hanken Grotesk",
    "category": "sans-serif",
    "advance": 0.985,
    "faces": [
      {
        "key": "hanken-grotesk-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Unbounded",
    "category": "sans-serif",
    "advance": 1.32,
    "faces": [
      {
        "key": "unbounded-wght",
        "weight": "200 900"
      }
    ]
  },
  {
    "family": "Epilogue",
    "category": "sans-serif",
    "advance": 1.06,
    "faces": [
      {
        "key": "epilogue-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Red Hat Display",
    "category": "sans-serif",
    "advance": 0.982,
    "faces": [
      {
        "key": "red-hat-display-wght",
        "weight": "300 900"
      }
    ]
  },
  {
    "family": "Public Sans",
    "category": "sans-serif",
    "advance": 1.021,
    "faces": [
      {
        "key": "public-sans-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Nunito",
    "category": "sans-serif",
    "advance": 1,
    "faces": [
      {
        "key": "nunito-wght",
        "weight": "200 1000"
      }
    ]
  },
  {
    "family": "Karla",
    "category": "sans-serif",
    "advance": 1.032,
    "faces": [
      {
        "key": "karla-wght",
        "weight": "200 800"
      }
    ]
  },
  {
    "family": "Mulish",
    "category": "sans-serif",
    "advance": 1.021,
    "faces": [
      {
        "key": "mulish-wght",
        "weight": "200 1000"
      }
    ]
  },
  {
    "family": "Oswald",
    "category": "sans-serif",
    "advance": 0.856,
    "faces": [
      {
        "key": "oswald-wght",
        "weight": "200 700"
      }
    ]
  },
  {
    "family": "Fraunces",
    "category": "serif",
    "advance": 1.06,
    "faces": [
      {
        "key": "fraunces-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Playfair Display",
    "category": "serif",
    "advance": 0.988,
    "faces": [
      {
        "key": "playfair-display-wght",
        "weight": "400 900"
      }
    ]
  },
  {
    "family": "Cormorant Garamond",
    "category": "serif",
    "advance": 0.88,
    "faces": [
      {
        "key": "cormorant-garamond-wght",
        "weight": "300 700"
      }
    ]
  },
  {
    "family": "EB Garamond",
    "category": "serif",
    "advance": 0.917,
    "faces": [
      {
        "key": "eb-garamond-wght",
        "weight": "400 800"
      }
    ]
  },
  {
    "family": "Lora",
    "category": "serif",
    "advance": 1.034,
    "faces": [
      {
        "key": "lora-wght",
        "weight": "400 700"
      }
    ]
  },
  {
    "family": "Newsreader",
    "category": "serif",
    "advance": 1.012,
    "faces": [
      {
        "key": "newsreader-wght",
        "weight": "200 800"
      }
    ]
  },
  {
    "family": "Source Serif 4",
    "category": "serif",
    "advance": 1.042,
    "faces": [
      {
        "key": "source-serif-4-wght",
        "weight": "200 900"
      }
    ]
  },
  {
    "family": "Merriweather",
    "category": "serif",
    "advance": 1.061,
    "faces": [
      {
        "key": "merriweather-wght",
        "weight": "300 900"
      }
    ]
  },
  {
    "family": "Crimson Pro",
    "category": "serif",
    "advance": 0.913,
    "faces": [
      {
        "key": "crimson-pro-wght",
        "weight": "200 900"
      }
    ]
  },
  {
    "family": "Bodoni Moda",
    "category": "serif",
    "advance": 1.043,
    "faces": [
      {
        "key": "bodoni-moda-wght",
        "weight": "400 900"
      }
    ]
  },
  {
    "family": "Literata",
    "category": "serif",
    "advance": 1.084,
    "faces": [
      {
        "key": "literata-wght",
        "weight": "200 900"
      }
    ]
  },
  {
    "family": "Libre Baskerville",
    "category": "serif",
    "advance": 1.147,
    "faces": [
      {
        "key": "libre-baskerville-wght",
        "weight": "400 700"
      }
    ]
  },
  {
    "family": "JetBrains Mono",
    "category": "monospace",
    "advance": 1.284,
    "faces": [
      {
        "key": "jetbrains-mono-wght",
        "weight": "100 800"
      }
    ]
  },
  {
    "family": "Fira Code",
    "category": "monospace",
    "advance": 1.284,
    "faces": [
      {
        "key": "fira-code-wght",
        "weight": "300 700"
      }
    ]
  },
  {
    "family": "Geist Mono",
    "category": "monospace",
    "advance": 1.284,
    "faces": [
      {
        "key": "geist-mono-wght",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Caveat",
    "category": "handwriting",
    "advance": 0.769,
    "faces": [
      {
        "key": "caveat-wght",
        "weight": "400 700"
      }
    ]
  },
  {
    "family": "Poppins",
    "category": "sans-serif",
    "advance": 1.068,
    "faces": [
      {
        "key": "poppins-400",
        "weight": "400"
      },
      {
        "key": "poppins-600",
        "weight": "600"
      },
      {
        "key": "poppins-700",
        "weight": "700"
      },
      {
        "key": "poppins-800",
        "weight": "800"
      },
      {
        "key": "poppins-900",
        "weight": "900"
      }
    ]
  },
  {
    "family": "Lato",
    "category": "sans-serif",
    "advance": 0.962,
    "faces": [
      {
        "key": "lato-400",
        "weight": "400"
      },
      {
        "key": "lato-700",
        "weight": "700"
      },
      {
        "key": "lato-900",
        "weight": "900"
      }
    ]
  },
  {
    "family": "Bebas Neue",
    "category": "sans-serif",
    "advance": 0.717,
    "faces": [
      {
        "key": "bebas-neue-400",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Anton",
    "category": "sans-serif",
    "advance": 0.865,
    "faces": [
      {
        "key": "anton-400",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Archivo Black",
    "category": "sans-serif",
    "advance": 1.216,
    "faces": [
      {
        "key": "archivo-black-400",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Abril Fatface",
    "category": "display",
    "advance": 1.008,
    "faces": [
      {
        "key": "abril-fatface-400",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "DM Serif Display",
    "category": "serif",
    "advance": 0.965,
    "faces": [
      {
        "key": "dm-serif-display-400",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Instrument Serif",
    "category": "serif",
    "advance": 0.739,
    "faces": [
      {
        "key": "instrument-serif-400",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Young Serif",
    "category": "serif",
    "advance": 1.113,
    "faces": [
      {
        "key": "young-serif-400",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Gloock",
    "category": "serif",
    "advance": 1.009,
    "faces": [
      {
        "key": "gloock-400",
        "weight": "100 900"
      }
    ]
  },
  {
    "family": "Space Mono",
    "category": "monospace",
    "advance": 1.309,
    "faces": [
      {
        "key": "space-mono-400",
        "weight": "400"
      },
      {
        "key": "space-mono-700",
        "weight": "700"
      }
    ]
  },
  {
    "family": "IBM Plex Mono",
    "category": "monospace",
    "advance": 1.284,
    "faces": [
      {
        "key": "ibm-plex-mono-400",
        "weight": "400"
      },
      {
        "key": "ibm-plex-mono-600",
        "weight": "600"
      },
      {
        "key": "ibm-plex-mono-700",
        "weight": "700"
      }
    ]
  },
  {
    "family": "DM Mono",
    "category": "monospace",
    "advance": 1.284,
    "faces": [
      {
        "key": "dm-mono-400",
        "weight": "100 900"
      }
    ]
  }
]
