// GENERATED by worker/video/scripts/fonts.mjs — the font files, as bundle URLs. Do not edit by hand:
// change the family list there and run it again (its header says how).
//
// Imported by the compositions only: every line below is a .woff2 the bundler turns
// into a URL, and Mocky's own test suite has no @fontsource package to resolve.

import f0 from '@fontsource-variable/inter/files/inter-latin-wght-normal.woff2'
import f0x from '@fontsource-variable/inter/files/inter-latin-ext-wght-normal.woff2'
import f1 from '@fontsource-variable/inter-tight/files/inter-tight-latin-wght-normal.woff2'
import f1x from '@fontsource-variable/inter-tight/files/inter-tight-latin-ext-wght-normal.woff2'
import f2 from '@fontsource-variable/manrope/files/manrope-latin-wght-normal.woff2'
import f2x from '@fontsource-variable/manrope/files/manrope-latin-ext-wght-normal.woff2'
import f3 from '@fontsource-variable/space-grotesk/files/space-grotesk-latin-wght-normal.woff2'
import f3x from '@fontsource-variable/space-grotesk/files/space-grotesk-latin-ext-wght-normal.woff2'
import f4 from '@fontsource-variable/dm-sans/files/dm-sans-latin-wght-normal.woff2'
import f4x from '@fontsource-variable/dm-sans/files/dm-sans-latin-ext-wght-normal.woff2'
import f5 from '@fontsource-variable/plus-jakarta-sans/files/plus-jakarta-sans-latin-wght-normal.woff2'
import f5x from '@fontsource-variable/plus-jakarta-sans/files/plus-jakarta-sans-latin-ext-wght-normal.woff2'
import f6 from '@fontsource-variable/outfit/files/outfit-latin-wght-normal.woff2'
import f6x from '@fontsource-variable/outfit/files/outfit-latin-ext-wght-normal.woff2'
import f7 from '@fontsource-variable/sora/files/sora-latin-wght-normal.woff2'
import f7x from '@fontsource-variable/sora/files/sora-latin-ext-wght-normal.woff2'
import f8 from '@fontsource-variable/syne/files/syne-latin-wght-normal.woff2'
import f8x from '@fontsource-variable/syne/files/syne-latin-ext-wght-normal.woff2'
import f9 from '@fontsource-variable/work-sans/files/work-sans-latin-wght-normal.woff2'
import f9x from '@fontsource-variable/work-sans/files/work-sans-latin-ext-wght-normal.woff2'
import f10 from '@fontsource-variable/ibm-plex-sans/files/ibm-plex-sans-latin-wght-normal.woff2'
import f10x from '@fontsource-variable/ibm-plex-sans/files/ibm-plex-sans-latin-ext-wght-normal.woff2'
import f11 from '@fontsource-variable/figtree/files/figtree-latin-wght-normal.woff2'
import f11x from '@fontsource-variable/figtree/files/figtree-latin-ext-wght-normal.woff2'
import f12 from '@fontsource-variable/rubik/files/rubik-latin-wght-normal.woff2'
import f12x from '@fontsource-variable/rubik/files/rubik-latin-ext-wght-normal.woff2'
import f13 from '@fontsource-variable/montserrat/files/montserrat-latin-wght-normal.woff2'
import f13x from '@fontsource-variable/montserrat/files/montserrat-latin-ext-wght-normal.woff2'
import f14 from '@fontsource-variable/open-sans/files/open-sans-latin-wght-normal.woff2'
import f14x from '@fontsource-variable/open-sans/files/open-sans-latin-ext-wght-normal.woff2'
import f15 from '@fontsource-variable/roboto/files/roboto-latin-wght-normal.woff2'
import f15x from '@fontsource-variable/roboto/files/roboto-latin-ext-wght-normal.woff2'
import f16 from '@fontsource-variable/raleway/files/raleway-latin-wght-normal.woff2'
import f16x from '@fontsource-variable/raleway/files/raleway-latin-ext-wght-normal.woff2'
import f17 from '@fontsource-variable/archivo/files/archivo-latin-wght-normal.woff2'
import f17x from '@fontsource-variable/archivo/files/archivo-latin-ext-wght-normal.woff2'
import f18 from '@fontsource-variable/urbanist/files/urbanist-latin-wght-normal.woff2'
import f18x from '@fontsource-variable/urbanist/files/urbanist-latin-ext-wght-normal.woff2'
import f19 from '@fontsource-variable/lexend/files/lexend-latin-wght-normal.woff2'
import f19x from '@fontsource-variable/lexend/files/lexend-latin-ext-wght-normal.woff2'
import f20 from '@fontsource-variable/onest/files/onest-latin-wght-normal.woff2'
import f20x from '@fontsource-variable/onest/files/onest-latin-ext-wght-normal.woff2'
import f21 from '@fontsource-variable/geist/files/geist-latin-wght-normal.woff2'
import f21x from '@fontsource-variable/geist/files/geist-latin-ext-wght-normal.woff2'
import f22 from '@fontsource-variable/instrument-sans/files/instrument-sans-latin-wght-normal.woff2'
import f22x from '@fontsource-variable/instrument-sans/files/instrument-sans-latin-ext-wght-normal.woff2'
import f23 from '@fontsource-variable/bricolage-grotesque/files/bricolage-grotesque-latin-wght-normal.woff2'
import f23x from '@fontsource-variable/bricolage-grotesque/files/bricolage-grotesque-latin-ext-wght-normal.woff2'
import f24 from '@fontsource-variable/schibsted-grotesk/files/schibsted-grotesk-latin-wght-normal.woff2'
import f24x from '@fontsource-variable/schibsted-grotesk/files/schibsted-grotesk-latin-ext-wght-normal.woff2'
import f25 from '@fontsource-variable/hanken-grotesk/files/hanken-grotesk-latin-wght-normal.woff2'
import f25x from '@fontsource-variable/hanken-grotesk/files/hanken-grotesk-latin-ext-wght-normal.woff2'
import f26 from '@fontsource-variable/unbounded/files/unbounded-latin-wght-normal.woff2'
import f26x from '@fontsource-variable/unbounded/files/unbounded-latin-ext-wght-normal.woff2'
import f27 from '@fontsource-variable/epilogue/files/epilogue-latin-wght-normal.woff2'
import f27x from '@fontsource-variable/epilogue/files/epilogue-latin-ext-wght-normal.woff2'
import f28 from '@fontsource-variable/red-hat-display/files/red-hat-display-latin-wght-normal.woff2'
import f28x from '@fontsource-variable/red-hat-display/files/red-hat-display-latin-ext-wght-normal.woff2'
import f29 from '@fontsource-variable/public-sans/files/public-sans-latin-wght-normal.woff2'
import f29x from '@fontsource-variable/public-sans/files/public-sans-latin-ext-wght-normal.woff2'
import f30 from '@fontsource-variable/nunito/files/nunito-latin-wght-normal.woff2'
import f30x from '@fontsource-variable/nunito/files/nunito-latin-ext-wght-normal.woff2'
import f31 from '@fontsource-variable/karla/files/karla-latin-wght-normal.woff2'
import f31x from '@fontsource-variable/karla/files/karla-latin-ext-wght-normal.woff2'
import f32 from '@fontsource-variable/mulish/files/mulish-latin-wght-normal.woff2'
import f32x from '@fontsource-variable/mulish/files/mulish-latin-ext-wght-normal.woff2'
import f33 from '@fontsource-variable/oswald/files/oswald-latin-wght-normal.woff2'
import f33x from '@fontsource-variable/oswald/files/oswald-latin-ext-wght-normal.woff2'
import f34 from '@fontsource-variable/fraunces/files/fraunces-latin-wght-normal.woff2'
import f34x from '@fontsource-variable/fraunces/files/fraunces-latin-ext-wght-normal.woff2'
import f35 from '@fontsource-variable/playfair-display/files/playfair-display-latin-wght-normal.woff2'
import f35x from '@fontsource-variable/playfair-display/files/playfair-display-latin-ext-wght-normal.woff2'
import f36 from '@fontsource-variable/cormorant-garamond/files/cormorant-garamond-latin-wght-normal.woff2'
import f36x from '@fontsource-variable/cormorant-garamond/files/cormorant-garamond-latin-ext-wght-normal.woff2'
import f37 from '@fontsource-variable/eb-garamond/files/eb-garamond-latin-wght-normal.woff2'
import f37x from '@fontsource-variable/eb-garamond/files/eb-garamond-latin-ext-wght-normal.woff2'
import f38 from '@fontsource-variable/lora/files/lora-latin-wght-normal.woff2'
import f38x from '@fontsource-variable/lora/files/lora-latin-ext-wght-normal.woff2'
import f39 from '@fontsource-variable/newsreader/files/newsreader-latin-wght-normal.woff2'
import f39x from '@fontsource-variable/newsreader/files/newsreader-latin-ext-wght-normal.woff2'
import f40 from '@fontsource-variable/source-serif-4/files/source-serif-4-latin-wght-normal.woff2'
import f40x from '@fontsource-variable/source-serif-4/files/source-serif-4-latin-ext-wght-normal.woff2'
import f41 from '@fontsource-variable/merriweather/files/merriweather-latin-wght-normal.woff2'
import f41x from '@fontsource-variable/merriweather/files/merriweather-latin-ext-wght-normal.woff2'
import f42 from '@fontsource-variable/crimson-pro/files/crimson-pro-latin-wght-normal.woff2'
import f42x from '@fontsource-variable/crimson-pro/files/crimson-pro-latin-ext-wght-normal.woff2'
import f43 from '@fontsource-variable/bodoni-moda/files/bodoni-moda-latin-wght-normal.woff2'
import f43x from '@fontsource-variable/bodoni-moda/files/bodoni-moda-latin-ext-wght-normal.woff2'
import f44 from '@fontsource-variable/literata/files/literata-latin-wght-normal.woff2'
import f44x from '@fontsource-variable/literata/files/literata-latin-ext-wght-normal.woff2'
import f45 from '@fontsource-variable/libre-baskerville/files/libre-baskerville-latin-wght-normal.woff2'
import f45x from '@fontsource-variable/libre-baskerville/files/libre-baskerville-latin-ext-wght-normal.woff2'
import f46 from '@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-wght-normal.woff2'
import f46x from '@fontsource-variable/jetbrains-mono/files/jetbrains-mono-latin-ext-wght-normal.woff2'
import f47 from '@fontsource-variable/fira-code/files/fira-code-latin-wght-normal.woff2'
import f47x from '@fontsource-variable/fira-code/files/fira-code-latin-ext-wght-normal.woff2'
import f48 from '@fontsource-variable/geist-mono/files/geist-mono-latin-wght-normal.woff2'
import f48x from '@fontsource-variable/geist-mono/files/geist-mono-latin-ext-wght-normal.woff2'
import f49 from '@fontsource-variable/caveat/files/caveat-latin-wght-normal.woff2'
import f49x from '@fontsource-variable/caveat/files/caveat-latin-ext-wght-normal.woff2'
import f50 from '@fontsource/poppins/files/poppins-latin-400-normal.woff2'
import f50x from '@fontsource/poppins/files/poppins-latin-ext-400-normal.woff2'
import f51 from '@fontsource/poppins/files/poppins-latin-600-normal.woff2'
import f51x from '@fontsource/poppins/files/poppins-latin-ext-600-normal.woff2'
import f52 from '@fontsource/poppins/files/poppins-latin-700-normal.woff2'
import f52x from '@fontsource/poppins/files/poppins-latin-ext-700-normal.woff2'
import f53 from '@fontsource/poppins/files/poppins-latin-800-normal.woff2'
import f53x from '@fontsource/poppins/files/poppins-latin-ext-800-normal.woff2'
import f54 from '@fontsource/poppins/files/poppins-latin-900-normal.woff2'
import f54x from '@fontsource/poppins/files/poppins-latin-ext-900-normal.woff2'
import f55 from '@fontsource/lato/files/lato-latin-400-normal.woff2'
import f55x from '@fontsource/lato/files/lato-latin-ext-400-normal.woff2'
import f56 from '@fontsource/lato/files/lato-latin-700-normal.woff2'
import f56x from '@fontsource/lato/files/lato-latin-ext-700-normal.woff2'
import f57 from '@fontsource/lato/files/lato-latin-900-normal.woff2'
import f57x from '@fontsource/lato/files/lato-latin-ext-900-normal.woff2'
import f58 from '@fontsource/bebas-neue/files/bebas-neue-latin-400-normal.woff2'
import f58x from '@fontsource/bebas-neue/files/bebas-neue-latin-ext-400-normal.woff2'
import f59 from '@fontsource/anton/files/anton-latin-400-normal.woff2'
import f59x from '@fontsource/anton/files/anton-latin-ext-400-normal.woff2'
import f60 from '@fontsource/archivo-black/files/archivo-black-latin-400-normal.woff2'
import f60x from '@fontsource/archivo-black/files/archivo-black-latin-ext-400-normal.woff2'
import f61 from '@fontsource/abril-fatface/files/abril-fatface-latin-400-normal.woff2'
import f61x from '@fontsource/abril-fatface/files/abril-fatface-latin-ext-400-normal.woff2'
import f62 from '@fontsource/dm-serif-display/files/dm-serif-display-latin-400-normal.woff2'
import f62x from '@fontsource/dm-serif-display/files/dm-serif-display-latin-ext-400-normal.woff2'
import f63 from '@fontsource/instrument-serif/files/instrument-serif-latin-400-normal.woff2'
import f63x from '@fontsource/instrument-serif/files/instrument-serif-latin-ext-400-normal.woff2'
import f64 from '@fontsource/young-serif/files/young-serif-latin-400-normal.woff2'
import f64x from '@fontsource/young-serif/files/young-serif-latin-ext-400-normal.woff2'
import f65 from '@fontsource/gloock/files/gloock-latin-400-normal.woff2'
import f65x from '@fontsource/gloock/files/gloock-latin-ext-400-normal.woff2'
import f66 from '@fontsource/space-mono/files/space-mono-latin-400-normal.woff2'
import f66x from '@fontsource/space-mono/files/space-mono-latin-ext-400-normal.woff2'
import f67 from '@fontsource/space-mono/files/space-mono-latin-700-normal.woff2'
import f67x from '@fontsource/space-mono/files/space-mono-latin-ext-700-normal.woff2'
import f68 from '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2'
import f68x from '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-ext-400-normal.woff2'
import f69 from '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-600-normal.woff2'
import f69x from '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-ext-600-normal.woff2'
import f70 from '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-700-normal.woff2'
import f70x from '@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-ext-700-normal.woff2'
import f71 from '@fontsource/dm-mono/files/dm-mono-latin-400-normal.woff2'
import f71x from '@fontsource/dm-mono/files/dm-mono-latin-ext-400-normal.woff2'

export const FONT_FILES = {
  'inter-wght': { latin: f0, latinExt: f0x },
  'inter-tight-wght': { latin: f1, latinExt: f1x },
  'manrope-wght': { latin: f2, latinExt: f2x },
  'space-grotesk-wght': { latin: f3, latinExt: f3x },
  'dm-sans-wght': { latin: f4, latinExt: f4x },
  'plus-jakarta-sans-wght': { latin: f5, latinExt: f5x },
  'outfit-wght': { latin: f6, latinExt: f6x },
  'sora-wght': { latin: f7, latinExt: f7x },
  'syne-wght': { latin: f8, latinExt: f8x },
  'work-sans-wght': { latin: f9, latinExt: f9x },
  'ibm-plex-sans-wght': { latin: f10, latinExt: f10x },
  'figtree-wght': { latin: f11, latinExt: f11x },
  'rubik-wght': { latin: f12, latinExt: f12x },
  'montserrat-wght': { latin: f13, latinExt: f13x },
  'open-sans-wght': { latin: f14, latinExt: f14x },
  'roboto-wght': { latin: f15, latinExt: f15x },
  'raleway-wght': { latin: f16, latinExt: f16x },
  'archivo-wght': { latin: f17, latinExt: f17x },
  'urbanist-wght': { latin: f18, latinExt: f18x },
  'lexend-wght': { latin: f19, latinExt: f19x },
  'onest-wght': { latin: f20, latinExt: f20x },
  'geist-wght': { latin: f21, latinExt: f21x },
  'instrument-sans-wght': { latin: f22, latinExt: f22x },
  'bricolage-grotesque-wght': { latin: f23, latinExt: f23x },
  'schibsted-grotesk-wght': { latin: f24, latinExt: f24x },
  'hanken-grotesk-wght': { latin: f25, latinExt: f25x },
  'unbounded-wght': { latin: f26, latinExt: f26x },
  'epilogue-wght': { latin: f27, latinExt: f27x },
  'red-hat-display-wght': { latin: f28, latinExt: f28x },
  'public-sans-wght': { latin: f29, latinExt: f29x },
  'nunito-wght': { latin: f30, latinExt: f30x },
  'karla-wght': { latin: f31, latinExt: f31x },
  'mulish-wght': { latin: f32, latinExt: f32x },
  'oswald-wght': { latin: f33, latinExt: f33x },
  'fraunces-wght': { latin: f34, latinExt: f34x },
  'playfair-display-wght': { latin: f35, latinExt: f35x },
  'cormorant-garamond-wght': { latin: f36, latinExt: f36x },
  'eb-garamond-wght': { latin: f37, latinExt: f37x },
  'lora-wght': { latin: f38, latinExt: f38x },
  'newsreader-wght': { latin: f39, latinExt: f39x },
  'source-serif-4-wght': { latin: f40, latinExt: f40x },
  'merriweather-wght': { latin: f41, latinExt: f41x },
  'crimson-pro-wght': { latin: f42, latinExt: f42x },
  'bodoni-moda-wght': { latin: f43, latinExt: f43x },
  'literata-wght': { latin: f44, latinExt: f44x },
  'libre-baskerville-wght': { latin: f45, latinExt: f45x },
  'jetbrains-mono-wght': { latin: f46, latinExt: f46x },
  'fira-code-wght': { latin: f47, latinExt: f47x },
  'geist-mono-wght': { latin: f48, latinExt: f48x },
  'caveat-wght': { latin: f49, latinExt: f49x },
  'poppins-400': { latin: f50, latinExt: f50x },
  'poppins-600': { latin: f51, latinExt: f51x },
  'poppins-700': { latin: f52, latinExt: f52x },
  'poppins-800': { latin: f53, latinExt: f53x },
  'poppins-900': { latin: f54, latinExt: f54x },
  'lato-400': { latin: f55, latinExt: f55x },
  'lato-700': { latin: f56, latinExt: f56x },
  'lato-900': { latin: f57, latinExt: f57x },
  'bebas-neue-400': { latin: f58, latinExt: f58x },
  'anton-400': { latin: f59, latinExt: f59x },
  'archivo-black-400': { latin: f60, latinExt: f60x },
  'abril-fatface-400': { latin: f61, latinExt: f61x },
  'dm-serif-display-400': { latin: f62, latinExt: f62x },
  'instrument-serif-400': { latin: f63, latinExt: f63x },
  'young-serif-400': { latin: f64, latinExt: f64x },
  'gloock-400': { latin: f65, latinExt: f65x },
  'space-mono-400': { latin: f66, latinExt: f66x },
  'space-mono-700': { latin: f67, latinExt: f67x },
  'ibm-plex-mono-400': { latin: f68, latinExt: f68x },
  'ibm-plex-mono-600': { latin: f69, latinExt: f69x },
  'ibm-plex-mono-700': { latin: f70, latinExt: f70x },
  'dm-mono-400': { latin: f71, latinExt: f71x },
}
